{{- if and .Values.mtls.enabled (not .Values.spire.enabled) }}
{{- $cn := printf "%s.%s.svc.cluster.local" (include "faultmesh.componentName" (dict "root" . "component" "control-plane")) .Release.Namespace -}}
{{- $altNames := list $cn (include "faultmesh.componentName" (dict "root" . "component" "control-plane")) "localhost" -}}
{{- $ca := genCA "faultmesh-dev-ca" 3650 -}}
{{- $server := genSignedCert $cn nil $altNames 3650 $ca -}}
{{- $client := genSignedCert "fm-agent" nil (list "fm-agent") 3650 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "faultmesh.componentName" (dict "root" . "component" "svid") }}
  labels:
    {{- include "faultmesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  server-svid.pem: |
{{ $server.Cert | indent 4 }}
  server-svid.key: |
{{ $server.Key | indent 4 }}
  client-svid.pem: |
{{ $client.Cert | indent 4 }}
  client-svid.key: |
{{ $client.Key | indent 4 }}
  bundle.pem: |
{{ $ca.Cert | indent 4 }}
{{- end }}
