apiVersion: v1
kind: ServiceAccount
metadata:
  name: fm-agent
  labels:
    {{- include "faultmesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fm-control-plane
  labels:
    {{- include "faultmesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fm-ctl
  labels:
    {{- include "faultmesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: ctl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fm-executor
  labels:
    {{- include "faultmesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: executor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fm-operator
  labels:
    {{- include "faultmesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
