// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: faultmesh/v1/telemetry.proto

package faultmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source    string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	AgentId   string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Metric
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_faultmesh_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_faultmesh_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_faultmesh_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetMetric() *MetricPoint {
	if x != nil {
		if x, ok := x.Payload.(*Event_Metric); ok {
			return x.Metric
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Metric struct {
	Metric *MetricPoint `protobuf:"bytes,10,opt,name=metric,proto3,oneof"`
}

func (*Event_Metric) isEvent_Payload() {}

type MetricPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_faultmesh_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_faultmesh_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_faultmesh_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *MetricPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_faultmesh_v1_telemetry_proto protoreflect.FileDescriptor

const file_faultmesh_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1cfaultmesh/v1/telemetry.proto\x12\ffaultmesh.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\x05Event\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x123\n" +
	"\x06metric\x18\n" +
	" \x01(\v2\x19.faultmesh.v1.MetricPointH\x00R\x06metricB\t\n" +
	"\apayload\"\xb1\x01\n" +
	"\vMetricPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12=\n" +
	"\x06labels\x18\x03 \x03(\v2%.faultmesh.v1.MetricPoint.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B<Z:faultmesh/data-plane/pkg/genproto/faultmesh/v1;faultmeshv1b\x06proto3"

var (
	file_faultmesh_v1_telemetry_proto_rawDescOnce sync.Once
	file_faultmesh_v1_telemetry_proto_rawDescData []byte
)

func file_faultmesh_v1_telemetry_proto_rawDescGZIP() []byte {
	file_faultmesh_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_faultmesh_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_faultmesh_v1_telemetry_proto_rawDesc), len(file_faultmesh_v1_telemetry_proto_rawDesc)))
	})
	return file_faultmesh_v1_telemetry_proto_rawDescData
}

var file_faultmesh_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_faultmesh_v1_telemetry_proto_goTypes = []any{
	(*Event)(nil),                 // 0: faultmesh.v1.Event
	(*MetricPoint)(nil),           // 1: faultmesh.v1.MetricPoint
	nil,                           // 2: faultmesh.v1.MetricPoint.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_faultmesh_v1_telemetry_proto_depIdxs = []int32{
	3, // 0: faultmesh.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: faultmesh.v1.Event.metric:type_name -> faultmesh.v1.MetricPoint
	2, // 2: faultmesh.v1.MetricPoint.labels:type_name -> faultmesh.v1.MetricPoint.LabelsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_faultmesh_v1_telemetry_proto_init() }
func file_faultmesh_v1_telemetry_proto_init() {
	if File_faultmesh_v1_telemetry_proto != nil {
		return
	}
	file_faultmesh_v1_telemetry_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Metric)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_faultmesh_v1_telemetry_proto_rawDesc), len(file_faultmesh_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_faultmesh_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_faultmesh_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_faultmesh_v1_telemetry_proto_msgTypes,
	}.Build()
	File_faultmesh_v1_telemetry_proto = out.File
	file_faultmesh_v1_telemetry_proto_goTypes = nil
	file_faultmesh_v1_telemetry_proto_depIdxs = nil
}
