imageRegistry: ""
imagePullPolicy: IfNotPresent

controlAddr: "fm-faultmesh-control-plane.faultmesh.svc.cluster.local:7777"

agent:
  image:
    repository: faultmesh/fm-agent
    tag: dev
  resources: {}

operator:
  replicas: 1
  image:
    repository: faultmesh/fm-operator
    tag: dev
  resources: {}

executor:
  replicas: 1
  image:
    repository: faultmesh/fm-executor
    tag: dev
  resources: {}

ctl:
  replicas: 1
  image:
    repository: faultmesh/fm-ctl
    tag: dev
  resources: {}

controlPlane:
  replicas: 2
  image:
    repository: faultmesh/control-plane
    tag: dev
  resources: {}
  persistence:
    size: 4Gi
    storageClassName: ""

mtls:
  enabled: false

spire:
  enabled: true
  trustDomain: faultmesh.local
  global:
    spire:
      clusterName: faultmesh
      trustDomain: faultmesh.local
      recommendations:
        enabled: true
  spire-server:
    caSubject:
      country: US
      organization: Faultmesh
      commonName: faultmesh-spire-ca
    controllerManager:
      identities:
        clusterSPIFFEIDs:
          default:
            enabled: false
  spiffe-csi-driver:
    fullnameOverride: spiffe-csi-driver

spiffe:
  socketPath: /run/spire/agents/spire-agent.sock
  serverID: "spiffe://faultmesh.local/ns/{{ .Release.Namespace }}/sa/fm-control-plane"
  agentID:  "spiffe://faultmesh.local/ns/{{ .Release.Namespace }}/sa/fm-agent"
